import type {Metadata} from "next";
import {Montserrat} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import React from "react";
import Footer from "@/components/Footer";

const inter = Montserrat({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Bhikharam Chandmal Rajuji",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <NavBar/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
